import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import * as React from 'react';
import { useState } from 'react'
import { Grid, Paper} from '@mui/material'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [chairGrids, setChairGrids] = useState(
    function(){
      const theArray = new Array<Boolean[]>(10);
      for (let x = 0; x < 10; x++) {
        theArray[x] = new Array<Boolean>(10);        
        for (let y = 0; y < 10; y++) {
          theArray[x][y] = true;
        }
      }
      return theArray;
    }()
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid container justifyContent="center" alignContent="center">
          <Grid item xs>
            <Paper>前</Paper>
          </Grid>
        {
          chairGrids.map((column, cindex) =>(
            <Grid container key={cindex} justifyContent="center" alignContent="center">
            {
              column.map((grid, gindex) =>
                ( 
                  <Grid item key={gindex} xs>
                    <Paper style={grid?{background:'#FFFFFF'}:{background:'#000000'}}>{grid.toString()}</Paper>
                  </Grid>
                )
              )
            }
            </Grid>
            ))
        }
          <Grid item xs>
            <Paper>後ろ</Paper>
          </Grid>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
